# 1段目: ビルド
FROM maven:3.9-eclipse-temurin-17 AS build

WORKDIR /workspace

COPY app-backend/pom.xml .
RUN mvn -f pom.xml dependency:go-offline

COPY app-backend/src ./src
RUN mvn -f pom.xml clean package -DskipTests

# 2段目: 実行
FROM eclipse-temurin:17-jre

WORKDIR /app

# target/app.jar をそのままコピー
COPY --from=build /workspace/target/app.jar app.jar

EXPOSE 8080

ENV SPRING_PROFILES_ACTIVE=local

ENTRYPOINT ["java", "-jar", "app.jar"]
